services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "${FRONTEND_PORT:-4000}:${FRONTEND_PORT:-4000}"
    environment:
      - PORT=${FRONTEND_PORT:-4000}
      - REACT_APP_WS_PORT=${BACKEND_PORT:-3000}
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://38.210.96.132:9098/TodoApp}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    expose:
      - 3000
networks:
  react-express:
